DEF_USER_MESSAGE = "user_message"
DEF_ASSISTANT_MESSAGE = "assistant_message"
DEF_SEARCH_DATABASE = "search_database"
DEF_STORE_DATABASE = "store_database"
DEF_REGISTRATION_SERVER = "registration_server"
